services:
  - type: web
    name: docrolds-api
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123
      - key: DATABASE_URL
        value: "postgresql://docsbackendstorage_user:t6RcsLJoTnzxJeywouFYQ8ReylfXP5zL@dpg-d5e55lshg0os73cc9560-a.oregon-postgres.render.com/docsbackendstorage"
    autoDeploy: true
