services:
  - type: web
    name: docrolds-api
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123
      - key: DATABASE_URL
        value: "postgresql://docrolds_user:ZfratVit7BdDHLsfVA28ojzSzvMZeTo6@dpg-d4gkhl7diees73avhc5g-a.oregon-postgres.render.com/docrolds"
    autoDeploy: true
